export const angryQuotes = [
    { quote: "Speak when you are angry and you will make the best speech you will ever regret.", author: "Ambrose Bierce" },
    { quote: "For every minute you remain angry, you give up sixty seconds of peace of mind.", author: "Ralph Waldo Emerson" },
    { quote: "Holding onto anger is like drinking poison and expecting the other person to die.", author: "Buddha" },
    { quote: "The best fighter is never angry.", author: "Lao Tzu" },
    { quote: "When anger rises, think of the consequences.", author: "Confucius" },
    { quote: "Anger is one letter short of danger.", author: "Eleanor Roosevelt" },
    { quote: "Bitterness is like cancer. It eats upon the host. But anger is like fire. It burns it all clean.", author: "Maya Angelou" },
    { quote: "A fool gives full vent to his anger, but a wise man keeps himself under control.", author: "Proverbs 29:11" },
    { quote: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
    { quote: "Anger is a wind which blows out the lamp of the mind.", author: "Robert Green Ingersoll" },
    { quote: "The more anger towards the past you carry in your heart, the less capable you are of loving in the present.", author: "Barbara De Angelis" },
    { quote: "Never go to bed mad. Stay up and fight.", author: "Phyllis Diller" },
    { quote: "People won’t have time for you if you are always angry or complaining.", author: "Stephen Hawking" },
    { quote: "I am not arguing, I’m just explaining why I’m right.", author: "Unknown" },
    { quote: "You will not be punished for your anger, you will be punished by your anger.", author: "Buddha" },
    { quote: "Anger dwells only in the bosom of fools.", author: "Albert Einstein" },
    { quote: "Anger makes you smaller, while forgiveness forces you to grow beyond what you were.", author: "Cherie Carter-Scott" },
    { quote: "Whatever is begun in anger ends in shame.", author: "Benjamin Franklin" },
    { quote: "Anger is never without a reason, but seldom a good one.", author: "Benjamin Franklin" },
    { quote: "Control your anger, or it will control you.", author: "Unknown" },
    { quote: "The best remedy for anger is delay.", author: "Brigham Young" },
    { quote: "Beware the fury of a patient man.", author: "John Dryden" },
    { quote: "Anger is often more hurtful than the injury that caused it.", author: "Unknown" },
    { quote: "A moment of patience in a moment of anger saves a thousand moments of regret.", author: "Ali Ibn Abi Talib" },
    { quote: "The greatest remedy for anger is delay.", author: "Seneca" },
    { quote: "Anger makes dull men witty, but it keeps them poor.", author: "Elizabeth I" },
    { quote: "If you are patient in one moment of anger, you will escape a hundred days of sorrow.", author: "Chinese Proverb" },
    { quote: "When people hurt you over and over, think of them like sandpaper. They may scratch and hurt you a bit, but in the end, you end up polished and they end up useless.", author: "Chris Colfer" },
    { quote: "Anger is a short madness.", author: "Horace" },
    { quote: "Sometimes you just have to stay silent, because no words can explain what’s going on in your mind and heart.", author: "Unknown" },
    { quote: "Anger is like fire. It burns the person holding it more than the one it's directed at.", author: "Unknown" },
    { quote: "Never get angry. Never make a threat. Reason with people.", author: "Mario Puzo" },
    { quote: "Hating someone is like burning down your own house to get rid of a rat.", author: "Harry Emerson Fosdick" },
    { quote: "Some people create their own storms and then get mad when it rains.", author: "Unknown" },
    { quote: "Anger doesn’t solve anything. It builds nothing, but it can destroy everything.", author: "Unknown" },
    { quote: "Speak when you are angry – and you will make the best speech you’ll ever regret.", author: "Laurence J. Peter" },
    { quote: "Anger is always more harmful than the insult that caused it.", author: "Chinese Proverb" },
    { quote: "Never reply when you’re angry. Never make a promise when you’re happy. Never make a decision when you’re sad.", author: "Unknown" },
    { quote: "Sometimes, the best response is no response.", author: "Unknown" },
    { quote: "Don’t make decisions when you’re angry. Don’t make promises when you’re happy.", author: "Unknown" },
    { quote: "Anger is a bad adviser.", author: "French Proverb" },
    { quote: "The fastest way to lose respect is to react in anger.", author: "Unknown" },
    { quote: "If what we are doing with our anger is not achieving the desired result, it would seem logical to try something different.", author: "Harriet Lerner" },
    { quote: "Getting angry at someone is like lighting yourself on fire and expecting the other person to choke on the smoke.", author: "Unknown" },
    { quote: "Learn to let go. Not everything needs a reaction.", author: "Unknown" },
    { quote: "Anger can be your worst enemy or your best teacher.", author: "Unknown" },
    { quote: "Sometimes, the best revenge is to simply ignore those who hurt you.", author: "Unknown" },
    { quote: "An angry mind is a narrow mind.", author: "Unknown" },
    { quote: "Don’t let the anger of others affect your inner peace.", author: "Unknown" },
    { quote: "Stay calm. Anger only fuels the fire of your enemies.", author: "Unknown" }
];
