export const excitedQuotes = [
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { quote: "Opportunities don’t happen, you create them.", author: "Chris Grosser" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Today is a great day to do something amazing!", author: "Unknown" },
    { quote: "Be so excited about your life that others can’t help but feel it too!", author: "Unknown" },
    { quote: "Dream big, work hard, stay focused, and surround yourself with good people.", author: "Unknown" },
    { quote: "The best is yet to come!", author: "Unknown" },
    { quote: "Be fearless in the pursuit of what sets your soul on fire.", author: "Jennifer Lee" },
    { quote: "Do more things that make you forget to check your phone.", author: "Unknown" },
    { quote: "Your energy is contagious! Keep spreading the excitement!", author: "Unknown" },
    { quote: "Every day is a fresh start—make it count!", author: "Unknown" },
    { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    { quote: "Excitement is contagious. Let’s spread it everywhere!", author: "Unknown" },
    { quote: "Don’t wait for opportunity. Create it!", author: "Unknown" },
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "Life isn’t about finding yourself. It’s about creating yourself.", author: "George Bernard Shaw" },
    { quote: "You have within you right now, everything you need to deal with whatever the world throws at you.", author: "Brian Tracy" },
    { quote: "Live your life with passion, with some drive, and with excitement!", author: "Jim Valvano" },
    { quote: "Make today so awesome that yesterday gets jealous.", author: "Unknown" },
    { quote: "Turn your dreams into plans and your plans into reality.", author: "Unknown" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "Surround yourself with people who fuel your passion!", author: "Unknown" },
    { quote: "Your vibe attracts your tribe!", author: "Unknown" },
    { quote: "The world is yours to explore! Go after it!", author: "Unknown" },
    { quote: "Today is your opportunity to build the tomorrow you want.", author: "Ken Poirot" },
    { quote: "Live each day as if your life has just begun.", author: "Johann Wolfgang Von Goethe" },
    { quote: "There is no limit to what you can achieve!", author: "Unknown" },
    { quote: "Your dreams don’t work unless you do!", author: "Unknown" },
    { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { quote: "Push yourself, because no one else is going to do it for you!", author: "Unknown" },
    { quote: "Make each day your masterpiece.", author: "John Wooden" },
    { quote: "Hustle until you no longer have to introduce yourself.", author: "Unknown" },
    { quote: "Every morning brings a new reason to be excited!", author: "Unknown" },
    { quote: "You were born to stand out. Embrace your uniqueness!", author: "Unknown" },
    { quote: "Take the risk or lose the chance!", author: "Unknown" },
    { quote: "Happiness is waking up with a purpose.", author: "Unknown" },
    { quote: "Excitement is the spark that ignites the fire of success!", author: "Unknown" },
    { quote: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { quote: "Your potential is endless! Go do what you were created to do!", author: "Unknown" },
    { quote: "Every day is a chance to change your life.", author: "Unknown" },
    { quote: "Never let small minds convince you that your dreams are too big.", author: "Unknown" },
    { quote: "Start each day with a grateful heart and an excited soul.", author: "Unknown" },
    { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Life’s too short for anything less than excitement and adventure!", author: "Unknown" },
    { quote: "Wake up, smile, and tell yourself: Today is going to be amazing!", author: "Unknown" },
    { quote: "You have one life. Live it with excitement!", author: "Unknown" }
];
