export const excitedQuotes = [
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { quote: "Opportunities don’t happen, you create them.", author: "Chris Grosser" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Today is a great day to do something amazing!", author: "Unknown" },
    { quote: "Be so excited about your life that others can’t help but feel it too!", author: "Unknown" },
    { quote: "Dream big, work hard, stay focused, and surround yourself with good people.", author: "Unknown" },
    { quote: "Each morning we are born again. What we do today is what matters most.", author: "Buddha" },
    { quote: "Be fearless in the pursuit of what sets your soul on fire.", author: "Jennifer Lee" },
    { quote: "Do more things that make you forget to check your phone.", author: "Unknown" },
    { quote: "Your energy is contagious! Keep spreading the excitement!", author: "Unknown" },
    { quote: "Start each day with a positive thought and a grateful heart.", author: "Roy T. Bennett" },
    { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    { quote: "Excitement is contagious. Let’s spread it everywhere!", author: "Unknown" },
    { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "Life isn’t about finding yourself. It’s about creating yourself.", author: "George Bernard Shaw" },
    { quote: "You have within you right now, everything you need to deal with whatever the world throws at you.", author: "Brian Tracy" },
    { quote: "Live your life with passion, with some drive, and with excitement!", author: "Jim Valvano" },
    { quote: "Wake up with determination. Go to bed with satisfaction.", author: "George Lorimer" },
    { quote: "Turn your dreams into plans and your plans into reality.", author: "Unknown" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "Surround yourself with people who fuel your passion!", author: "Unknown" },
    { quote: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "Today is your opportunity to build the tomorrow you want.", author: "Ken Poirot" },
    { quote: "Live each day as if your life has just begun.", author: "Johann Wolfgang Von Goethe" },
    { quote: "There is no limit to what you can achieve!", author: "Unknown" },
    { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { quote: "Make each day your masterpiece.", author: "John Wooden" },
    { quote: "Hustle until you no longer have to introduce yourself.", author: "Unknown" },
    { quote: "A day without laughter is a day wasted.", author: "Charlie Chaplin" },
    { quote: "You were born to stand out. Embrace your uniqueness!", author: "Unknown" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "Happiness is waking up with a purpose.", author: "Unknown" },
    { quote: "Be so good they can’t ignore you.", author: "Steve Martin" },
    { quote: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { quote: "Your potential is endless! Go do what you were created to do!", author: "Unknown" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "Take risks: if you win, you will be happy; if you lose, you will be wise.", author: "Unknown" },
    { quote: "Start each day with a grateful heart and an excited soul.", author: "Unknown" },
    { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Life’s too short for anything less than excitement and adventure!", author: "Unknown" },
    { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "You have one life. Live it with excitement!", author: "Unknown" }
];
