export const happyQuotes = [
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon" },
    { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
    { quote: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
    { quote: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
    { quote: "The best way to cheer yourself is to try to cheer someone else up.", author: "Mark Twain" },
    { quote: "A smile is happiness you’ll find right under your nose.", author: "Tom Wilson" },
    { quote: "Count your age by friends, not years. Count your life by smiles, not tears.", author: " John Lennon" },
    { quote: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt" },
    { quote: "The key to being happy is knowing you have the power to choose what to accept and what to let go.", author: "Dodinsky" },
    { quote: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { quote: "Being happy never goes out of style.", author: "Lilly Pulitzer" },
    { quote: "Happiness is not out there, it’s in you.", author: "Unknown" },
    { quote: "Be happy with what you have. Be excited about what you want.", author: "Alan Cohen" },
    { quote: "The most important thing is to enjoy your life—to be happy—it’s all that matters.", author: "Audrey Hepburn" },
    { quote: "Happiness is not having what you want. It is appreciating what you have.", author: "Unknown" },
    { quote: "They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.", author: "Tom Bodett" },
    { quote: "The happiest people don’t have the best of everything, they just make the best of everything.", author: "Unknown" },
    { quote: "If you want to be happy, be.", author: "Leo Tolstoy" },
    { quote: "A joyful heart is the inevitable result of a heart burning with love.", author: "Mother Teresa" },
    { quote: "Joy is not in things; it is in us.", author: "Richard Wagner" },
    { quote: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
    { quote: "Enjoy the little things in life, for one day you may look back and realize they were the big things.", author: "Robert Brault" },
    { quote: "Happiness is not a station you arrive at, but a manner of traveling.", author: "Margaret Lee Runbeck" },
    { quote: "Happiness shared is happiness doubled.", author: "Swedish Proverb" },
    { quote: "Success is getting what you want, happiness is wanting what you get", author: "W.P. Kinsella" },
    { quote: "A happy heart makes the face cheerful.", author: "Proverbs 15:13" },
    { quote: "Life is better when you’re laughing.", author: "Unknown" },
    { quote: "The only joy in the world is to begin.", author: "Cesare Pavese" },
    { quote: "Happiness quite unshared can scarcely be called happiness; it has no taste.", author: "Charlotte Bronte" },
    { quote: "A day without laughter is a day wasted.", author: "Charlie Chaplin" },
    { quote: "Happiness is a habit—cultivate it.", author: "Elbert Hubbard" },
    { quote: "Happiness is a state of mind. It’s just according to the way you look at things.", author: "Walt Disney" },
    { quote: "A positive attitude gives you power over your circumstances instead of your circumstances having power over you.", author: "Joyce Meyer" },
    { quote: "Happiness is a journey, not a destination.", author: "Ben Sweetland" },
    { quote: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
    { quote: "Be the reason someone smiles today.", author: "Unknown" },
    { quote: "Let your smile change the world, but don’t let the world change your smile.", author: "Unknown" },
    { quote: "Happiness in intelligent people is the rarest thing I know.", author: "Ernest Hemingway, The Garden of Eden" },
    { quote: "Happiness looks good on you.", author: "Unknown" },
    { quote: "The happiest people make the best of everything.", author: "Unknown" },
    { quote: "Being happy isn't having everything in your life be perfect. Maybe it's about stringing together all the little things.", author: "Ann Brashares" },
    { quote: "You deserve to be happy. You deserve to live a life you are excited about.", author: "Unknown" },
    { quote: "Sometimes happiness is a feeling. Sometimes it's a decision.", author: "Unknown" },
    { quote: "Happiness is an inside job.", author: "William Arthur Ward" },
    { quote: "The secret of happiness is freedom, the secret of freedom is courage.", author: "Thucydides" },
    { quote: "Live every moment, laugh every day, love beyond words.", author: "Unknown" },
    { quote: "Joy is the simplest form of gratitude.", author: "Karl Barth" }
];
