export const sadQuotes = [
    { quote: "Tears come from the heart and not from the brain.", author: "Leonardo da Vinci" },
    { quote: "Sometimes, we create our own heartbreaks through expectation.", author: "Unknown" },
    { quote: "It’s sad when someone you know becomes someone you knew.", author: "Henry Rollins" },
    { quote: "The saddest thing about love is that not only that it cannot last forever, but that heartbreak is soon forgotten.", author: "William Faulkner" },
    { quote: "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", author: "Christopher Morley" },
    { quote: "There is no greater sorrow than to recall happiness in times of misery.", author: "Dante Alighieri" },
    { quote: "When you’re happy, you enjoy the music. But when you’re sad, you understand the lyrics.", author: "Frank Ocean" },
    { quote: "It’s amazing how someone can break your heart and you can still love them with all the little pieces.", author: "Ella Harper" },
    { quote: "The word ‘happy’ would lose its meaning if it were not balanced by sadness.", author: "Carl Jung" },
    { quote: "Some people are going to leave, but that’s not the end of your story. That’s the end of their part in your story.", author: "Faraaz Kazi" },
    { quote: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
    { quote: "Behind every sweet smile, there is a bitter sadness that no one can see.", author: "Tupac Shakur" },
    { quote: "Sad things happen. They do. But we don’t need to live sad forever.", author: "Mattie Stepanek" },
    { quote: "You can’t be strong all the time. Sometimes you just need to be alone and let your tears out.", author: "Unknown" },
    { quote: "Grief is not as heavy as guilt, but it takes more away from you.", author: "Veronica Roth" },
    { quote: "Loneliness and the feeling of being unwanted is the most terrible poverty.", author: "Mother Teresa" },
    { quote: "Crying doesn’t mean that you’re weak. Since birth, it’s always been a sign that you’re alive.", author: "Unknown" },
    { quote: "Sadness is but a wall between two gardens.", author: "Kahlil Gibran" },
    { quote: "You know, a heart can be broken, but it keeps on beating, just the same..", author: "Fannie Flagg" },
    { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "When you’re happy, you enjoy the music but when you’re sad, you understand the lyrics.", author: "Frank Ocean" },
    { quote: "Never make someone a priority when all you are to them is an option.", author: "Maya Angelou" },
    { quote: "The pain of parting is nothing to the joy of meeting again.", author: "Charles Dickens" },
    { quote: "Pain is inevitable. Suffering is optional.", author: "Haruki Murakami" },
    { quote: "What is coming is better than what is gone.", author: "Unknown" },
    { quote: "Crying is how your heart speaks when your lips can’t explain the pain you feel.", author: "Unknown" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "Nothing hurts more than being disappointed by the one person you thought would never hurt you.", author: "Unknown" },
    { quote: "Please remember that you’re capable, brave and loved – even when it feels like you’re not.", author: "Unknown" },
    { quote: "You can wipe away tears, but the heart will always remember the pain.", author: "Unknown" },
    { quote: "Every situation in life is temporary. So, when life is good, make sure you enjoy and receive it fully. And when life is not so good, remember that it will not last forever and better days are on the way.", author: "Jenni Young" },
    { quote: "The worst feeling is not being lonely, it’s being forgotten by someone you can’t forget.", author: "Unknown" },
    { quote: "Always try to end the day with a positive thought. No matter how hard things are, tomorrow is a fresh opportunity to make everything better.", author: "Unknown" },
    { quote: "At some point, you have to realize that some people can stay in your heart but not in your life.", author: "Unknown" },
    { quote: "It’s okay to cry. It’s okay to not be okay.", author: "Unknown" },
    { quote: "The scars you can’t see are the hardest to heal.", author: "Astrid Alauda" },
    { quote: "Sometimes you don’t realize the weight of something you’ve been carrying until you feel the weight of its release.", author: "Unknown" },
    { quote: "Sadness is the price we pay for love.", author: "Queen Elizabeth II" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "You alone are enough. You have nothing to prove to anybody.", author: "Maya Angelou" },
    { quote: "There is a time for departure even when there’s no certain place to go.", author: "Tennessee Williams" },
    { quote: "I don’t think of all the misery, but of the beauty that still remains.", author: "Anne Frank" },
    { quote: "The soul would have no rainbow if the eyes had no tears.", author: "Native American Proverb" },
    { quote: "The hardest part about walking away from someone is the part where you realize that no matter how slowly you go, they will never run after you.", author: "Unknown" },
    { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
    { quote: "One day, you’ll realize that some people are meant to stay in your heart, but not in your life.", author: "Unknown" },
    { quote: "You are living. You occupy space. You have a mass. You matter.", author: "Albert Einstein" },
    { quote: "No matter what people tell you, words and ideas can change the world.", author: "Robin Williams" }
];
