export const tiredQuotes = [
    { quote: "You don’t always have to be strong. Sometimes, you just need to rest and recharge.", author: "Unknown" },
    { quote: "Fatigue is the best pillow.", author: "Benjamin Franklin" },
    { quote: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid" },
    { quote: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
    { quote: "Tired minds don’t plan well. Sleep first, plan later.", author: "Walter Reisch" },
    { quote: "Run when you can, walk if you have to, crawl if you must; just never give up.", author: "Dean Karnazes" },
    { quote: "You can't pour from an empty cup. Take care of yourself first.", author: "Unknown" },
    { quote: "Sleep is the golden chain that ties health and our bodies together.", author: "Thomas Dekker" },
    { quote: "It’s okay to feel tired. It means you’re doing something meaningful.", author: "Unknown" },
    { quote: "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.", author: "George Horace Lorimer" },
    { quote: "Sometimes the most productive thing you can do is relax.", author: "Mark Black" },
    { quote: "If you get tired, learn to rest, not to quit.", author: "Banksy" },
    { quote: "The more you lose yourself in something bigger than yourself, the more energy you will have.", author: "Norman Vincent Peale" },
    { quote: "Sleep is the best meditation.", author: "Dalai Lama" },
    { quote: "Rest is not a luxury; it’s a necessity.", author: "Unknown" },
    { quote: "Burnout is what happens when you try to avoid being human for too long.", author: "Michael Gungor" },
    { quote: "A weary body needs rest, but a weary soul needs peace.", author: "Unknown" },
    { quote: "Even the strongest need to pause and catch their breath.", author: "Unknown" },
    { quote: "Fatigue makes cowards of us all.", author: "Vince Lombardi" },
    { quote: "Sometimes the best thing you can do is close your eyes and take a deep breath.", author: "Unknown" },
    { quote: "You are allowed to be both a masterpiece and a work in progress at the same time.", author: "Sophia Bush" },
    { quote: "Being tired doesn’t mean you’re weak. It means you’ve been strong for too long.", author: "Unknown" },
    { quote: "Rest when you’re weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", author: "Ralph Marston" },
    { quote: "Some days, even getting out of bed feels like a victory.", author: "Unknown" },
    { quote: "No one is perfect. That’s why pencils have erasers and people need rest.", author: "Unknown" },
    { quote: "When life knocks you down, roll over and take a nap.", author: "Unknown" },
    { quote: "You’re not lazy, you’re just tired. And that’s okay.", author: "Unknown" },
    { quote: "Even the biggest heroes turn into cowards when they get tired.", author: "Mirko Cro Cop" },
    { quote: "It’s okay to take a step back and recharge.", author: "Unknown" },
    { quote: "Breathe. You are doing better than you think you are.", author: "Unknown" },
    { quote: "Rest is a form of self-respect.", author: "Unknown" },
    { quote: "If you want to make an easy job seem mighty hard, just keep putting off doing it.", author: "Olin Miller" },
    { quote: "You deserve rest just as much as you deserve success.", author: "Unknown" },
    { quote: "Listen to your body. It knows when to rest.", author: "Unknown" },
    { quote: "It’s not that I’m so smart, it’s just that I stay with problems longer.", author: "Albert Einstein" },
    { quote: "Even the sun needs to set to rise again.", author: "Unknown" },
    { quote: "Don’t push yourself so hard that you forget to live.", author: "Unknown" },
    { quote: "Sometimes the bravest thing you can do is admit you’re tired.", author: "Unknown" },
    { quote: "Fatigue should never be mistaken for failure.", author: "Unknown" },
    { quote: "Rest isn’t wasted time. It’s part of the journey.", author: "Unknown" },
    { quote: "You can’t heal if you don’t rest.", author: "Unknown" },
    { quote: "Even machines need to shut down for maintenance.", author: "Unknown" },
    { quote: "One good nap can solve a lot of problems.", author: "Unknown" },
    { quote: "Tomorrow needs you. Get some rest today.", author: "Unknown" },
    { quote: "Rest. Reset. Restart.", author: "Unknown" },
    { quote: "Give yourself permission to take it easy.", author: "Unknown" },
    { quote: "A river cuts through a rock not because of its power, but its persistence.", author: "Jim Watkins" },
    { quote: "Taking time to rest isn’t selfish; it’s essential.", author: "Unknown" },
    { quote: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso" }
];
